default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: bucketlist_p8o3
  pool: 5
  timeout: 5000
  host: dpg-cihuo0l9aq012eog39dg-a
  username: soundmoney254
  password: ixBq2VCAEdggeVCVSsIiw8YDYazel3YO
